import fs from 'node:fs';
const base='https://api.cdn.visitjeju.net/photomng/imgpath/';
const photos=[
['스누피가든','202012/16/66b81cd9-d2b0-48ab-a782-08e91cf9d5a3.webp','CNTS_200000000010956'],
['스누피가든 야외 정원','202012/16/79a19069-d0c9-40f1-860b-b2fd53a84d36.webp','CNTS_200000000010956'],
['에코랜드 테마파크','202506/10/a118f398-a6a4-4745-9feb-3685520d0c69.webp','CONT_000000000500438'],
['세화해변','202407/24/a6e518e7-2d5c-45ab-9c6e-93218d6f1082.webp','CONT_000000000500361'],
['성읍민속마을','202409/06/cf7e9f6b-178f-4d3d-b978-91beb5145a10.webp','CONT_000000000500351'],
['보롬왓','202111/01/8d53044e-93fc-48aa-bc43-2f6fa270026b.webp','CNTS_000000000020050'],
['서귀포 KAL 호텔','201804/30/07742d0b-7654-49d0-9919-ecfb80815cf7.webp','CONT_000000000500926'],
['아쿠아플라넷 제주','202408/21/d596736a-c82a-4ec6-ad55-2fe2c8f9a977.webp','CONT_000000000500565']];
const source=p=>'https://www.visitjeju.net/kr/detail/view?contentsid='+p[2];
const gallery=`<section id="photos" class="block wrap"><p class="eyebrow">PICTURE YOUR DAYS</p><h2>사진으로 먼저 만나는 제주</h2><p>일정에 있는 장소를 사진으로 비교해 보세요. 사진은 관광안내 자료이며 현재 개화 상태·기상·시설 배치를 보장하지 않습니다.</p><div class="gallery">${photos.map(p=>`<figure><a href="${source(p)}" target="_blank" rel="noopener noreferrer"><img loading="lazy" decoding="async" src="${base+p[1]}" alt="${p[0]} 관광안내 사진" width="800" height="540"></a><figcaption><b>${p[0]}</b><br><a href="${source(p)}" target="_blank" rel="noopener noreferrer">사진 출처: 제주관광공사 VisitJeju ↗</a></figcaption></figure>`).join('')}</div></section>`;
const details=`<section id="details" class="block wrap"><p class="eyebrow">THE PRACTICAL DETAILS</p><h2>현장에서 바로 보는 상세 안내</h2><div class="trend"><div><h3>스누피가든 2시간, 이렇게 나누기</h3><p><b>09:45–10:25</b> 실내 가든하우스 → <b>10:25–10:40</b> 화장실·물·앉아서 휴식 → <b>10:40–11:20</b> 야외에서 좋아하는 캐릭터와 사진 → <b>11:20–11:45</b> 카페·기념품.</p><p>위 시간은 A·B·C안 기준 관람 제안입니다. D안은 첫날 12:55–14:25에 실내 40분·휴식 15분·가까운 야외 35분으로 줄여 관람합니다. 입장할 때 안내 지도로 짧은 경로를 고르세요. 동행인은 쉬는 장소를 정하고 아이들은 보호자와 가까운 구역을 둘러보면 편합니다.</p><p>유모차는 개인 지참을 권장하며 대여를 전제로 계획하지 않았습니다. 아이가 지치면 야외를 줄이고 바로 점심으로 이동하세요.</p></div><div><h3>에코랜드는 ‘모든 역 완주’보다 선택</h3><p><b>09:40</b> 입장·기차 대기 → <b>10:00 전후</b> 기차로 이동 → <b>10:20–10:50</b> 한 구간 산책 → <b>10:50–11:20</b> 복귀 여유.</p><p>기차 시각표가 아닌 계획 예시입니다. 실제 배차·승하차 규정을 현장에서 확인하고, 열차가 붐비면 산책 구간을 줄이세요. 일행이 함께 앉을 수 있도록 이동을 서두르지 않습니다.</p><p>유모차 접기·보관 조건, 막차와 우천 운행은 공식 안내를 확인하세요.</p></div><div><h3>주차부터 식사까지, 한 번에</h3><p><b>도도리:</b> 주차 후 보호자 한 명이 자리·주문을 확인하고 나머지는 아이 화장실을 챙기기. 짐은 차 밖에서 보이지 않게 정리.</p><p><b>숙성도:</b> 함덕점은 2층이므로 동행인 계단 이용이 불편하면 엘리베이터 여부부터 전화 확인. 일행 한 테이블과 카시트가 아닌 유아용 의자 필요 여부도 함께 전달.</p><p><b>다른 식당:</b> 예약·주차장을 확정하지 않았습니다. 지도에서 당일 운영을 보고 전화로 일행 좌석을 확인한 뒤 출발하세요.</p></div><div><h3>호텔을 옮기는 22일</h3><p>전날 밤 큰 가방을 정리하고, 차 안에는 <b>아이 옷·간식·물·물티슈·상비용품</b>만 따로 꺼내 두세요. 체크아웃 전 충전기·냉장고·욕실을 확인합니다.</p><p>점심 후 서귀포로 내려가는 구간을 낮잠 시간으로 쓰되, 차에서 못 자면 중간에 쉬고 호텔 관광을 생략하세요. 도착이 빨라도 객실이 준비됐다고 가정하지 않습니다.</p><p>예약한 객실 수·정원은 예약 내용을 기준으로 확인하세요.</p></div></div>
<h3>날짜별 선택·생략 기준</h3><div class="tablewrap"><table><thead><tr><th>날짜</th><th>꼭 지킬 것</th><th>컨디션이 좋을 때</th><th>피곤하거나 비가 오면</th></tr></thead><tbody><tr><td>20일</td><td>10시 인수 · 도도리 · 소노벨 휴식 / D안은 스누피 추가</td><td>함덕 평지 20분</td><td>산책 생략, 숙성도는 21일로 이동</td></tr><tr><td>21일</td><td>A·B·C 스누피 / D 함덕 휴식 / E 베이글·스누피·동화마을</td><td>B안 세화 카페</td><td>스누피 실내 중심, 세화 생략</td></tr><tr><td>22일</td><td>소노벨 체크아웃 · 서귀포 KAL 입실</td><td>A·D 숲기차 / B 들판·마을 / C 생물관람 / E 제주당·해지개</td><td>관광 체류 축소, 호텔 입실 뒤 쉬기</td></tr><tr><td>23일</td><td>10시 허니문하우스 조식 · 11시 출발 · 14시 반납 · 16:05 항공</td><td>공항권에서 짧은 음료 휴식</td><td>카페 대기가 길면 포장·간식으로 전환, 11시 출발 준수</td></tr></tbody></table></div>
<details class="check"><summary><b>전날 밤과 매일 아침 준비물</b></summary><ul><li>성인 신분증, 아이 항공 탑승용 서류, 연령 할인 증빙, 숙소·렌터카 예약 정보.</li><li>필요한 카시트 장착 확인, 유모차 접었을 때 짐칸 여유 확인, 멀미 시 쉬어갈 지점 준비.</li><li>아이별 여벌옷 1세트, 모자, 물, 간식, 물티슈, 작은 수건, 익숙한 책·스티커.</li><li>동행인 개인 복용약·편한 신발, 가벼운 겉옷, 휴대폰 충전기.</li><li>당일 핵심 장소 1곳의 운영·휴무 확인, 점심 후보 전화, 귀가일 반납 주소 저장.</li></ul></details></section>`;
let html=fs.readFileSync('dist/index.html','utf8');
html=html.replace('</style>',`.gallery{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:18px}.gallery figure{background:white;border:1px solid var(--line);border-radius:8px;overflow:hidden}.gallery img{width:100%;height:175px;object-fit:cover;border-radius:0}.gallery figcaption{padding:12px;font-size:14px}.gallery figcaption a{font-size:12px}.tablewrap{overflow-x:auto;margin:18px 0 28px}table{border-collapse:collapse;width:100%;min-width:580px;background:white;font-size:15px}th,td{text-align:left;vertical-align:top;padding:15px;border:1px solid var(--line)}th{background:var(--pale)}summary{cursor:pointer;padding:8px 0}@media(max-width:850px){.gallery{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:500px){.gallery{grid-template-columns:1fr}.gallery img{height:230px}} </style>`);
html=html.replace('<a href="#places">','<a href="#photos">사진 보기</a><a href="#details">상세 준비</a><a href="#places">');
html=html.replace('<section id="places"',gallery+details+'<section id="places"');
html=html.replace('COAST DAYS / JEJU','TRIP / JEJU');
html=html.replace('사진: <a','장소 사진은 VisitJeju 원문 이미지를 연결하며 권리는 각 권리자에게 있습니다. 원본 촬영시점과 여행일의 모습은 다를 수 있습니다.</p><p>함덕 사진: <a');
fs.writeFileSync('dist/index.html',html);fs.writeFileSync('photos.json',JSON.stringify(photos.map(p=>({name:p[0],url:base+p[1],source:source(p)})),null,2));
const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));for(const m of html.matchAll(/href="#([^"]+)"/g))if(!ids.has(m[1]))throw Error(m[1]);console.log({images:(html.match(/<img /g)||[]).length,bytes:Buffer.byteLength(html),anchors:ids.size});
